### ISSUE TITLE
v1.4.0-rc.3 won't start

### ISSUE THREAD

**Issue by dlnilsson** [Dygmalab/Bazecor#743]
**Describe the bug**
can't start [v1.4.0-rc.3](https://github.com/Dygmalab/Bazecor/releases/tag/v1.4.0-rc.3) on windows, clean install (removed %APPDATA%/Bazecor)

**Screenshots**

![image](https://github.com/Dygmalab/Bazecor/assets/1218385/d0c2b1a8-9e72-46be-86e9-d126d1a17696)

log:
````
DevTools failed to load source map: Could not load content for file:///C:/Users/XXXXXX/AppData/Local/Bazecor/app-1.4.0-rc3/resources/app/.webpack/renderer/main_window/index.js.map: Unexpected end of JSON input
index.js:8 Retrieving settings:  {backupFolder: 'C:\\Users\\XXXXXX\\Dygma\\Backups', backupFrequency: 0, language: 'english', darkMode: 'system', showDefaults: false, …}
index.js:8 Font face:  FontFace {family: 'Libre Franklin', style: 'normal', weight: 'normal', stretch: 'normal', unicodeRange: 'U+0-10FFFF', …}
index.js:8 settings already upgraded, returning
index.js:8 SerialPort devices find: [{…}]
index.js:8 Usable found devices: [{…}]
index.js:8 Usable found devices: [HIDDevice]
index.js:8 Checking:  HIDDevice {device: {…}, oninputreport: null, opened: false, vendorId: 13807, productId: 18, …}
index.js:8 checking if device is connected:  0 false
index.js:8 checking if device is supported:  0
index.js:8 Trying to connect HID
index.js:8 Checking connected & supported:  true false
index.js:6469 Devices Available: [Device]
index.js:8 TypeError: Cannot read properties of undefined (reading 'find')
    at index.js:6469:1139
    at Array.map (<anonymous>)
    at index.js:6469:814
    at index.js:6469:1956
    at ol (index.js:8:1233943)
    at kd (index.js:8:1254065)
    at index.js:8:1250669
    at w (index.js:8:1435039)
    at Immediate.I [as _onImmediate] (index.js:8:1435571)
    at process.processImmediate (node:internal/timers:476:21)
ps @ index.js:8
n.callback @ index.js:8
Fi @ index.js:8
vl @ index.js:8
xl @ index.js:8
Al @ index.js:8
(anonymous) @ index.js:8
wd @ index.js:8
dd @ index.js:8
$o @ index.js:8
kd @ index.js:8
(anonymous) @ index.js:8
w @ index.js:8
I @ index.js:8
processImmediate @ node:internal/timers:476
````
**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Bazecor Version:v1.4.0-rc.3

**Comment by panosz** [comment]
same problem in ubuntu. I have also tried with `rc.2` and I am seeing the same screen as @dlnilsson with both versions, along with this message printed in the terminal:

```
[20818:0315/002255.911281:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.portal.Error.NotFound: Requested setting not found
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

removing USB Listeners
```

**Comment by skvvara** [comment]
That is because there is missing "neurons" key in config file. A workaround until it gets fixed is to add it. Open `%AppData%\Bazecor\config.json` add `, "neurons": []` so it looks like this:

```
{
    "settings": {
        "backupFolder": "C:\\Users\\XXXXXX\\Dygma\\Backups",
        "backupFrequency": 0,
        "language": "english",
        "darkMode": "system",
        "showDefaults": false,
        "isStandardView": true,
        "allowBeta": true
    },
    "neurons": []
}
```

**Comment by alexpargon** [comment]
Hey there @skvvara ! yes, that's the case, i just fixed it myself but seeing you already created a PR, i will merge yours 👍🏻
