### ISSUE TITLE
Bug in v1.4.0-rc.3 breaks all previous bazecor versions

### ISSUE THREAD

**Issue by Kry0geniX** [Dygmalab/Bazecor#751]
**Describe the bug**
[v1.4.0-rc.3](https://github.com/Dygmalab/Bazecor/releases/tag/v1.4.0-rc.3) Fails to run and keyboard cannot be scanned by any version of dygma regardless of version used

**To Reproduce**
1. Download latest app image release, assign execute permission bit
2. Run bazecor 1.4.0-rc.3

**Screenshots**
Bazecor v1.1.2 after running latest release
![image](https://github.com/Dygmalab/Bazecor/assets/24844025/77d31fb4-1507-477e-86b9-198e7fcc15ba)

**Desktop (please complete the following information):**
 - OS: Endeavour OS using linux xanmod kernel
 - Bazecor Version: ALL

**Additional context**
Logs from dygma v1.4.0 with --trace-warnings flag:
Note: The libva error has existed for all previous versions of Dygma used and hasn't caused a problem, I'm working on fixing that today and will update with any further info I can find  

`
❯ ./Bazecor-1.4.0-rc.3-x64.AppImage --trace-warnings
adding USB Listeners
(node:115538) UnhandledPromiseRejectionWarning: Error: Config schema violation: `neurons/0/macros/1/actions/0/keyCode` must be number
    at e.exports._validate (/tmp/.mount_BazecolL0oTx/usr/lib/bazecor/resources/app/.webpack/main/index.js:2:18757)
    at get store [as store] (/tmp/.mount_BazecolL0oTx/usr/lib/bazecor/resources/app/.webpack/main/index.js:2:17478)
    at new T (/tmp/.mount_BazecolL0oTx/usr/lib/bazecor/resources/app/.webpack/main/index.js:2:15219)
    at new e.exports (/tmp/.mount_BazecolL0oTx/usr/lib/bazecor/resources/app/.webpack/main/index.js:8:44527)
    at i.getStore (/tmp/.mount_BazecolL0oTx/usr/lib/bazecor/resources/app/.webpack/main/index.js:8:197674)
    at t.default (/tmp/.mount_BazecolL0oTx/usr/lib/bazecor/resources/app/.webpack/main/index.js:8:207102)
    at /tmp/.mount_BazecolL0oTx/usr/lib/bazecor/resources/app/.webpack/main/index.js:8:194611
    at Generator.next (<anonymous>)
    at /tmp/.mount_BazecolL0oTx/usr/lib/bazecor/resources/app/.webpack/main/index.js:8:194269
    at new Promise (<anonymous>)
    at emitUnhandledRejectionWarning (node:internal/process/promises:200:15)
    at processPromiseRejections (node:internal/process/promises:296:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
(node:115538) Error: Config schema violation: `neurons/0/macros/1/actions/0/keyCode` must be number
    at e.exports._validate (/tmp/.mount_BazecolL0oTx/usr/lib/bazecor/resources/app/.webpack/main/index.js:2:18757)
    at get store [as store] (/tmp/.mount_BazecolL0oTx/usr/lib/bazecor/resources/app/.webpack/main/index.js:2:17478)
    at new T (/tmp/.mount_BazecolL0oTx/usr/lib/bazecor/resources/app/.webpack/main/index.js:2:15219)
    at new e.exports (/tmp/.mount_BazecolL0oTx/usr/lib/bazecor/resources/app/.webpack/main/index.js:8:44527)
    at i.getStore (/tmp/.mount_BazecolL0oTx/usr/lib/bazecor/resources/app/.webpack/main/index.js:8:197674)
    at t.default (/tmp/.mount_BazecolL0oTx/usr/lib/bazecor/resources/app/.webpack/main/index.js:8:207102)
    at /tmp/.mount_BazecolL0oTx/usr/lib/bazecor/resources/app/.webpack/main/index.js:8:194611
    at Generator.next (<anonymous>)
    at /tmp/.mount_BazecolL0oTx/usr/lib/bazecor/resources/app/.webpack/main/index.js:8:194269
    at new Promise (<anonymous>)
[115538:0322/110901.716802:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
libva error: vaGetDriverNames() failed with unknown libva error`

**Comment by skvvara** [comment]
The cause for this is the type of keyCode field for macro's action item. JSON Schema says it's number but in reality it may be an array eg. macro contains delay with random value.
